const MessageType = Object.freeze( {
    SESSION_INITIALIZING: 'SESSION_INITIALIZING',
    SESSION_INITIALIZED:  'SESSION_INITIALIZED',
    AUTH: 'AUTH',
    SERVICE_CREATE: 'SERVICE_CREATE',
    HEARTBEAT: 'HEARTBEAT',
    INITIAL_DATA: 'INITIAL_DATA',
    DATA: 'DATA',
    DATA_ACK: 'DATA_ACK',
    DATA_CLOSE: 'DATA_CLOSE',
    ERROR: 'ERROR',
});

export default MessageType;